/**:
  sfgenerator:
    ros__parameters:
      use_sim_time: true
      grid_map_frame_id: robot_base_footprint
      filter_plugins: ['voxel_downsample', stat_outlier_removal]
      stat_outlier_removal:
        plugin: 'sfframework/StatisticalOutlierRemovalFilter'
        nb_neighbors: 30
        std_ratio: 2.0
      voxel_downsample:
        plugin: 'sfframework/VoxelDownSampleFilter'
        voxel_size: 0.2
      default_filters:
        max_distance: 10.0
        max_height: 1.5
        min_height: -2.0
      partitioner_plugins: ['trivial_plane', 'dbscan']
      # sfframework/TrivialPlaneSegmentation
      trivial_plane:
        plugin: 'sfframework/TrivialPlaneSegmentation'
        distance_threshold: 0.1
      dbscan:
        input_tags: ['ground']
        invert_selection: true
        plugin: 'sfframework/DBSCAN'
      sf_strategy_plugins: ['gaussian_repulsion', 'sdf', 'parabolic_rest', 'plane_inclination', 'weighted_summation']
      gaussian_repulsion:
        plugin: 'sfframework/GaussianRepulsion'
        input_tags: ['clusters']
      sdf:
        plugin: 'sfframework/DistanceField1'
        input_tags: ['clusters']
        seer_frame_id: robot_top_lidar_link
      parabolic_rest:
        plugin: 'sfframework/ParabolicRest'
      plane_inclination:
        input_tag: ground
        output_layer: plane_inclination
        plugin: sfframework/PlaneInclination
      weighted_summation:
        plugin: 'sfframework/WeightedSummation'
        input_layers: ['gaussian_repulsion', 'parabolic_rest', 'plane_inclination']
        weights: [0.5, 0.5, 0.5]

      partitioned_pointcloud_visualization:
        display_outliers: true
        display_inliers: true
        inliers_considered: ['ground', 'clusters']
        colors:
          outliers:
            min: [255, 255, 255]
          ground:
            min: [57, 196, 94]
          clusters:
            min: [127, 0, 0]
            max: [255, 255, 0]
